# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-05-15 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_instance_id', models.CharField(max_length=50)),
                ('service_id', models.CharField(max_length=50)),
                ('plan_id', models.CharField(max_length=50)),
                ('organization_guid', models.CharField(max_length=50)),
                ('space_guid', models.CharField(max_length=50)),
            ],
        ),
    ]
