# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-05-15 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokerApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerecord',
            name='service_instance_id',
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='organization_guid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='plan_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='service_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='space_guid',
            field=models.CharField(max_length=100),
        ),
    ]
